# Generated by Django 4.1 on 2024-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='runningTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='starRate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
