# Generated by Django 4.1 on 2024-01-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_createyear_alter_review_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genres',
            field=models.CharField(choices=[('SF', 'SF'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Music', 'Music'), ('Horror', 'Horror')], max_length=200),
        ),
    ]
