# Generated by Django 4.1 on 2024-01-12 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='runningTime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='starRate',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
