# Generated by Django 4.1 on 2024-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='defaultName', max_length=10),
        ),
    ]
