# Generated by Django 4.1 on 2024-01-15 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_user_age_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='market',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='market',
            name='market_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.markethistory'),
        ),
        migrations.AddField(
            model_name='user',
            name='market_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.markethistory'),
        ),
    ]
